### PR TITLE
Making weather card responsive

### LINKED ISSUE #7: Improve mobile usability
The card that displays the weather information isn't responsive. It's far too narrow on mobile, and too wide on desktop. Can you look into making it be an appropriate size on all screen sizes.

### PR DESCRIPTION
**Pull request by dans77777**
fixes #7

I made weather card responsive  appropriate size on all screen sizes. Attaching screenshots for your reference @NoahCardoz
Screenshot (19)
Screenshot (20)
a

### CODE REVIEW

**Review by drishtipeshwani — COMMENTED** [review]
Saw the preview and even went through the code. Everything looks good to me 👍

**Review by Sargam-Agarwal — APPROVED** [review]
Everything looks good to me too 👍

**Comment by dans77777** [comment]
hey @NoahCardoza other podmates have reviewed my code. it looks good, if it seems good to you, could you please merge this PR?

**Comment by NoahCardoza** [comment]
Sure thing, I didn't know it was ready since it was still marked as a draft PR.

All looks good!

**Comment by NoahCardoza** [comment]
Actually, after marking the PR ready to merge it found some conflicts. Can you take a look at those?

**Comment by dans77777** [comment]
@NoahCardoza  I have resolved conflicts by new branch **resolved-conflicts/issue-7** and updated pull request. if everything seems good to you, can you please merge to main branch?

**Review by NoahCardoza — APPROVED** [review]
LGTM!

**Pull request merged**
