### PR TITLE
Change background and Some UI Changes

### LINKED ISSUE #2: Change the colour scheme based on temperature / weather type
Change the websites appearance to match the weather conditions. The Apple Weather app has some cool examples in iOS 15, check them out [here](https://9to5mac.com/2021/09/24/ios-15-weather-app-hands-on/).

### PR DESCRIPTION
**Pull request by EkjotKaur**
## Please, go through these steps before you submit a PR.

Fixes: #2  

- [x] My Pod Leader knows I'm working on this Pull Request
- [x] I've explained what the Pull Request is adding.
- [x] I've explained why this is important.

Clouds

Clear

Smoke

@NoahCardoza Please view this PR.

### CODE REVIEW

**Comment by NoahCardoza** [comment]
Everything looks really good!

Not sure if there is an issue with how you are calling the API but for some reason, it can't find "Santa Cruz, CA" a city near me. Just typing "Santa Cruz" returns a country in Bolivia.

Also, when a city is not found it might be a good idea to mention that rather than keep the "Loading..." message because then the user will never know it failed under the hood.

**Comment by EkjotKaur** [comment]
This is an API for searching by the name of the city.

This results from adding a space
image

This is the result without the space
image

**Comment by NoahCardoza** [comment]
> This is an API for searching by the name of the city.
> 
> This results from adding a space image
> 
> This is the result without the space image

Very weird, I think it's probably the API being weird then. I forgot to mention but if I search "Santa Cruz, US" then it works. I guess it recognizes the country code but not the state code.

**Comment by NoahCardoza** [comment]
I just merged your last PR but it seems to have caused some merge conflicts. Sorry!

**Comment by EkjotKaur** [comment]
@NoahCardoza, I have resolved the conflicts.

**Comment by NoahCardoza** [comment]
Looks great!

**Pull request merged**
