### PR TITLE
Geolocation

### LINKED ISSUE #3: Using Geolocation API to get the users location
Using the Geolocation API to get the users location as the first weather results displayed, instead of just New York City.

Read more [here](https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API).

### PR DESCRIPTION
**Pull request by shravani05**
Resolves #3 
Used the Geolocation API to get the users location as the first weather results displayed, instead of just New York City.
Used bigdatacloud API to get city name from latitude and longitude.

### CODE REVIEW

**Comment by shravani05** [comment]
@NoahCardoza can you please review this pr?

**Comment by shravani05** [comment]
@Bhavika-Gianey @helenduz can you please review this pr?

**Comment by Bhavika-Gianey** [comment]
LGTM

**Review by Bhavika-Gianey — APPROVED** [review]
Went through the code. LGTM.

**Comment by shravani05** [comment]
@helenduz can you please go through the pr and approve the changes if there are no issues?

**Review by helenduz — APPROVED** [review]
Looks good and works well!

**Comment by shravani05** [comment]
Thank you @Bhavika-Gianey and @helenduz for reviewing the pr!

**Pull request merged**
