### PR TITLE
Autocomplete for cities

### PR DESCRIPTION
**Pull request by dhwaj1902**
Fixes for issue #6 

### Dev setup for this to work
 - Signup or Login to Google Maps API.
 - Create your places API under the dashboard section.
 - Assign your "API Key" to REACT_APP_GOOGLE_MAPS_API_KEY in the .env file.

### Description
 - I have implemented the react autocomplete places using google API.
 - Update the ``.env.example`` file (I have added ``REACT_APP_GOOGLE_MAPS_API_KEY``).
 - After autocompletion, it uses the coordinates received from Google Maps to query for current weather.

### Preview
https://user-images.githubusercontent.com/57860123/142240627-b24880c0-a3df-4947-b768-9573104d36b3.mp4

@NoahCardoza please review this PR.

### CODE REVIEW

**Comment by NoahCardoza** [comment]
Looking good! I'm waiting to merge #10, then you can fix any conflicts, and then I'll merge it. Good work! If you want to PM the API key to me over Discord I can add it to the Netlify build.

**Comment by dhwaj1902** [comment]
@NoahCardoza I have resolved all the conflicts.

**Review by Sargam-Agarwal — APPROVED** [review]
LGTM 👍🏻

**Review by drishtipeshwani — COMMENTED** [review]
Code looks good to me 👍. I was not able to preview it, probably because the API Key has not been added to Netlify.

**Comment by NoahCardoza** [comment]
> Code looks good to me 👍. I was not able to preview it, probably because the API Key has not been added to Netlify.

Good catch!

@dhwaj1902 can you send me the API key via Discord so I can add it to the Netlify build? Thanks!

**Comment by dhwaj1902** [comment]
> Good catch!
> 
> @dhwaj1902 can you send me the API key via Discord so I can add it to the Netlify build? Thanks!

I have PM you on Discord please check.

**Pull request merged**
