### PR TITLE
Fix Geolocation Error

### LINKED ISSUE #32: Geolocation Error
Not showing the user's geolocation weather at the starting. 
geolocation

### PR DESCRIPTION
**Pull request by Pratyush1606**
Fixes #32 

Actually, in Pull Request #17, the geolocation is setting `city` and then using that value for displaying the corresponding weather. But in the merged version, `cityCoordinates` is being used to get the result. 

In #17,
`
fetch(
      "https://api.openweathermap.org/data/2.5/weather?q=" +
        city +
        "&units=metric" +
        "&appid=" +
        process.env.REACT_APP_APIKEY
    )
`

In the current main version,
`
fetch(
      "https://api.openweathermap.org/data/2.5/weather?lat=" +
        cityCoordinates.lat +
        "&lon=" +
        cityCoordinates.lon +
        "&units=metric" +
        "&appid=" +
        process.env.REACT_APP_APIKEY
    )
`

### CODE REVIEW

**Comment by shravani05** [comment]
@Pratyush1606 LGTM

**Review by shravani05 — APPROVED** [review]

**Comment by NoahCardoza** [comment]
It seems like this feature it's working for me on macOS Chrome:

image

**Comment by Pratyush1606** [comment]
@NoahCardoza Are you talking about the preview of this pr or the main one?

**Review by DinuBotan — APPROVED** [review]
LGTM

**Comment by NoahCardoza** [comment]
> @NoahCardoza Are you talking about the preview of this pr or the main one?

Maybe I'm not clear on what this PR does. I expected it would make sure the city name in the search bar matched the name in the card:

image

In this image the card says "San Jose" but the search bar says "New York".

However, after rereading your description, maybe that's wasn't within the scope of your PR?

**Comment by shravani05** [comment]
@NoahCardoza yes right, this pr just detects location using geolocation api

**Comment by NoahCardoza** [comment]
LGTM, just a small merge conflict.

**Comment by Pratyush1606** [comment]
@NoahCardoza Resolved the conflict :)

**Pull request merged**
